name: Deploy to Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # 👇 Build steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
      - name: Install dependencies
        run: npm install 
      - name: generate json of file structure
        run: bash generate-table-json.sh
      - name: fetch team json
        run : bash sync-data.sh 
      - name: Build
        run: npm run build
      - name: show build size
        run : du -sh build
      # 👆 Build steps
      # Conditionally execute the following steps only on main branch push
      - name: Setup Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3
      - name: Upload artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v2

